name: build and publish

on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'manual build and publish'
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        games: [ dontstarve, satisfactory ]

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up TAG
        run: |
          echo "TAG=$(date +"%y.%U")" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: VergilGao
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.games }}
          push: true
          tags: |
            ghcr.io/vergilgao/steamcmd-${{ matrix.games }}-server:${{ env.TAG }}
            ghcr.io/vergilgao/steamcmd-${{ matrix.games }}-server:latest

      - name: delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 30